# Generated by Django 3.2.8 on 2021-10-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_remove_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
