# Generated by Django 3.2.8 on 2021-10-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_body',
            new_name='comments',
        ),
    ]
